# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Ultralytics YOLO11 object detection model with P3/8 - P5/32 outputs
# Model docs: https://docs.ultralytics.com/models/yolo11
# Task docs: https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolo11n.yaml' will call yolo11.yaml with scale 'n'
  # [depth, width, max_channels]
  #n: [0.50, 0.25, 1024] # summary: 181 layers, 2624080 parameters, 2624064 gradients, 6.6 GFLOPs
  #s: [0.50, 0.50, 1024] # summary: 181 layers, 9458752 parameters, 9458736 gradients, 21.7 GFLOPs
  m: [0.50, 1.00, 512] # summary: 231 layers, 20114688 parameters, 20114672 gradients, 68.5 GFLOPs
  #l: [1.00, 1.00, 512] # summary: 357 layers, 25372160 parameters, 25372144 gradients, 87.6 GFLOPs
  #x: [1.00, 1.50, 512] # summary: 357 layers, 56966176 parameters, 56966160 gradients, 196.0 GFLOPs

# YOLO11n backbone
backbone:
  # [from, repeats, module, args]

  ## Phase only ##   
  - [-1, 1, PhaseIFFT_1, [1,False]] # 0
  
  ## RGB YOLO11 backbone ##
  - [-2, 1, Conv, [64, 3, 2]] # 1   
  # p2 (no use)
  - [-1, 1, Conv, [128, 3, 2]] # 2
  - [-1, 2, C3k2, [256, False, 0.25]] #3
  
  # p3 (small)
  - [-1, 1, Conv, [256, 3, 2]] # 4
  - [-1, 2, C3k2, [512, False, 0.25]] # 5
  
  # p4 (medium)
  - [-1, 1, Conv, [512, 3, 2]] # 6
  - [-1, 2, C3k2, [512, True]] # 7
  
  # p5 (large)
  - [-1, 1, Conv, [1024, 3, 2]] # 8
  - [-1, 2, C3k2, [1024, True]] # 9
  - [-1, 1, SPPF, [1024, 5]] # 10
  - [-1, 2, C2PSA, [1024]] # 11
 
  ## FFT backbone ##
  - [0, 1, Conv, [64, 3, 2]] # 12   
  # p2 (no use)
  - [-1, 1, Conv, [128, 3, 2]] # 13
  - [-1, 2, C3k2, [256, False, 0.25]] # 14
  # p3
  - [-1, 1, Conv, [256, 3, 2]] # 15
  - [-1, 2, C3k2, [512, False, 0.25]] # 16
  # p4
  - [-1, 1, Conv, [512, 3, 2]] # 17
  - [-1, 2, C3k2, [512, True]] # 18
  # p5
  - [-1, 1, Conv, [1024, 3, 2]] # 19
  - [-1, 2, C3k2, [1024, True]] # 20
  - [-1, 1, SPPF, [1024, 5]] # 21
  - [-1, 2, C2PSA, [1024]] # 22

  # fused P3(add)
  - [5, 16, Add, [256]]  # 23 index 예시: RGB P3 + FFT P3 → 23
  # fused P4(add)
  - [7, 18, Add, [512]]  # 24 RGB P4 + FFT P4 → 24
  # fused P5 (add)
  - [11, 22, Add, [1024]] # 25 RGB P5 + FFT P5 → 25

# YOLO11n head
head:
  - [25, 1, nn.Upsample, [None, 2, "nearest"]] # 26: upsample fused P5
  - [[-1, 24], 1, Concat, [1]] # 27 cat backbone fused P4
  - [-1, 2, C3k2, [512, False]] # 28 : it is head P4

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]] # 29: upsample 28
  - [[-1, 23], 1, Concat, [1]] # 30: cat backbone fused P3
  - [-1, 2, C3k2, [256, False]] # 31: (final P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]] # 32
  - [[-1, 28], 1, Concat, [1]] # 33: cat head P4
  - [-1, 2, C3k2, [512, False]] # 34: (final P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]] # 35
  - [[-1, 25], 1, Concat, [1]] # 36 : cat head fused P5
  - [-1, 2, C3k2, [1024, True]] # 37 (final P5/32-large)

  - [[31, 34, 37], 1, Detect, [nc]] # Detect(P3, P4, P5)
